### ISSUE TITLE
安装好 转换后 启动报错warning: Indirect calls to "require" will not be bundled (surround with a try/catch to silence this warning)

### ISSUE THREAD

**Issue by tom-hanks** [tnfe/wp2vite#34] opened 2021-08-23 06:22 UTC
![image](https://user-images.githubusercontent.com/22985129/130400013-63d49919-b5d8-4838-8111-0ef93227f60c.png)

**Comment by dravenww** [comment] 2021-08-25 02:14
Duplicate of #32

**Closed as completed by dravenww** 2021-08-25 02:14 UTC
